### ISSUE TITLE
Support hexbgr

### ISSUE THREAD

**Issue by martinlindhe** [chriskempson/base16#116]
While converting https://github.com/chriskempson/base16-builder/blob/master/templates/conemu/conemu.xml.erb#L4 for use with builder 0.9 I wished there was support for "hexbgr".

This seems to have been supported in the old base16-builder project.

It is needed for conemu as seen in the above link.

I am currently working around it by doing

```xml
<value name="ColorTable00" type="dword" data="00{{base00-hex-b}}{{base00-hex-g}}{{base00-hex-r}}"/>
```

which works, but is tedious and error-prone.

The name of the new variable could be `{{base00-hexbgr}}` or `{{base00-hex-bgr}}`

**Comment by belak** [comment]
I've added this in the latest version of the go builder. This seems like a pretty useful idea.

**Comment by jonasnordlund** [comment]
This will also be essential for a Visual Studio (that is, not VS Code) template.

**Comment by belak** [comment]
Thankfully there's a workaround (as mentioned above) and there are builders which support it. I agree that it would be nice to have in the spec though.

**Comment by belak** [comment]
It's sufficient, but we also provide `base00-hex` as a convenience for `{{base00-hex-r}}{{base00-hex-g}}{{base00-hex-b}}`. rgb is definitely the most common, but bgr is also used in multiple templates.

At least in my opinion, it's fine to not officially support it because there's a workaround... but if that's the case this issue should be closed.
