### ISSUE TITLE
Help address an issue on base16-mintty?

### ISSUE THREAD

**Issue by iamthad** [chriskempson/base16#131]
I have an issue on one of the template repos I manage (iamthad/base16-mintty#1) which is expressing some confusion about the way the base16 schemes work. I'm not entirely sure how to respond to the issue.

Can anyone help me convey the way the base16 schemes work to resolve that user's confusion?

**Comment by chriskempson** [comment]
Perhaps it is best to explain that if you want the theme your terminal you should using base16-shell. You should only be using a terminal emulator theme if you are unable to use or don't want to use base16-shell.

Using base16-shell gives you compatibility with existing CLI/TUI applications by honouring the original colours whilst also allowing the use of additional colours that have been assigned to colours 17-21.

If you are unable to use if you are unable to use or don't want to use base16-shell then some applications will not appear correctly or will require theming in order to function correctly. One such example is `ls` with colour output.
