### ISSUE TITLE
Website and README don't communicate the usefulness of base16

### ISSUE THREAD

**Issue by mk12** [chriskempson/base16#174]
I love base16, but it took me a long time to figure out what's useful about it. For me, the killer feature is being able to configure things once -- either with a base16 plugin like for vim, or just sticking to the 8 ANSI colors for simpler things like tmux -- and then switch color themes in _everything_ with a single click in my terminal emulator preferences. It all immediately updates, even in vim (in tmux (in ssh (in another tmux (etc.)))). Before base16, if I wanted to switch from solarized to monokai, it would be a time-consuming ordeal -- I would have to change terminal colors, find the corresponding vim plugin, update vimrc, copy vimrc to remote machines, reinstall plugins, reload vims. Or at the very least change the colorscheme in each open vim if I had some mega colorscheme plugin.

None of this works properly when using [base16-shell][1] and you have both local and remote sessions. And when using termguicolors in vim, local vims won't update immediately either. So for me these things defeat the purpose of base16.

~~(As an aside, it seems like most of the complexity from this project is for supporting the base16-shell use case. For my use case, I never actually need the huge list of files generated for anything except iTerm2. The rest (vim, mainly) just always use base16-default-dark.)~~ Edit: Never mind, this is ignoring all the GUI programs it works for.

I could try writing something about this for the README if people think it would be useful.

[1]: https://github.com/chriskempson/base16-shell

**Comment by MarioRicalde** [comment]
@mk12 I find myself struggling to see what are the benefits of base16 too. It's unclear.

@mk12 are you still using this?

**Comment by mk12** [comment]
@MarioRicalde Yes, I'm still using it. I think it has two purposes:

- It allows theme **designers** to select a palette of 16 colours once and then instantly generate theme files for many different applications.
- It allows **users** to choose a colour theme they know will be available for all their applications.

However, as I said in my first comment, to me these reasons are not that compelling. What is compelling to me:

- It allows **terminal users** to configure all their CLI programs (tmux, vim, emacs, fzf, etc.) to use the default base 16 colour palette. Then, in their terminal preferences they can change the palette (by choosing a different base16 theme, e.g., going from Solarized Light to Solarized Dark) and everything will instantly reflect the change, without needed to go and change .vimrc, .emacs, etc.

This works because those themes use the 16 ANSI colour numbers rather than concretely specifying the colour. So there is a level of indirection. It also only works to the extent that all themes can use the same mapping from UI elements/syntax to colour numbers, and just change the palette. Which admittedly doesn't work perfectly for all themes, but it works well enough.

**Comment by MarioRicalde** [comment]
@mk12 Thank you for the explanation, that's what I've been wondering about. What pushed me away and made me slightly confused was the base16-shell repository. Which clearly would defeat the purpose of that. I'd really like to hear something from @chriskempson about what you've said. 

And if it's accurate it really should be SOMEWHERE.

**Comment by belak** [comment]
base16-shell is an interesting concept that I think falls flat in many instances because of how finicky it is and how hard it can be to configure.

If you look at the base16 colors, you'll see 8 different colors and 8 shades of gray. This works great for themes (and there are reasons for all these colors in the docs). However, in a terminal you generally have 16 colors - 8 normal and 8 "bright" versions of those colors. If you use the base16 terminal schemes, you'll end up with your "bright" colors as shades of gray, which isn't normally what you want.

However, if you use the 256 color versions of those themes, it copies the first 8 base16 colors into both the 8 normal and 8 bright. This is usually good enough for terminals, but means you're missing the last 8 base16 colors to use for themes. base16-shell is a method of loading the additional colors into the next 8 colors of your terminal (if it supports setting exact colors for colors after the 16 ansi colors). This means if you're using the compatible base16 terminal scheme, base16-shell scheme, and base16 editor scheme (vim and emacs both support this), you can use all 16 of the colors while still having terminal/shell colors which make sense.

**Comment by mk12** [comment]
@belak I use the base16 terminal themes without base16-shell, and the bright colours are mostly grey as you say (it's actually only 6 of them; brred and brcyan are not grey in most of the themes). I haven't found this to be a problem in practice, though. Programs that use generic ansi colours don't seem to use the bright ones that much, or in a way that base16 greys makes jarring. It *would* probably work poorly if your terminal is configured to show bold text using bright colours, but with iTerm2 I can configure it to show normal colours in bold font.

**Comment by chriskempson** [comment]
Agreed, for some people, it's just a set of themes they can download for a couple of programs of their choosing, for others they can use a builder to create their own themes. Not sure how to communicate this well.

**Comment by chriskempson** [comment]
@belak Agreed, b16shell can be a bit of a pain but I know of no better solution.

**Comment by PayasR** [comment]
A better README would be a huge help! I've been fiddling around with this repo, the base16-shell and the various base16-builder-<lang> pages for over an hour now, and I still have no clue what goes where and why. The builder did download things and generate a ton of files, but where am I to keep those files? do I use the base16-shell or base16-builder? Why are they two separate things? 
I'm sorry, nothing works, and I'm confused. Happy new year!

**Comment by belak** [comment]
base16-builder is generally for package maintainers. It’s designed to take template repositories and build themes based on all the color schemes.

Most repositories have their own installation methods, as many apps have different plugin systems. As an example, there are Emacs packages provided to make installation easier, but something else like a terminal theme you would have to download and install separately.

**Comment by PayasR** [comment]
So, is the base16-shell for the users then? I see it installs to .config/base16-shell. I've added the profile scripts to the fish shell init script, and now the terminal has commands for changing the base16-[themes]. Now how do I use the vim/alacritty themes? Don't I need the builder for that?

**Comment by belak** [comment]
base16-shell is for users. It's sort of a workaround. It's described in the README for that repo (https://github.com/chriskempson/base16-shell). Because base16 has 8 colors that are generally shades of grey, those don't line up with ANSI terminal colors... so if you do all of the following, it uses the same colors for normal and bright terminal colors and provides the leftovers in the 256 colorspace.

1. Use a terminal that supports 256 colors and changing the colorspace
2. Use a 256 color variant of your terminal color scheme.
3. Use base16 shell.
4. Use themes for terminal applications that understand to use the colors provided by base16-shell.

The base16-vim repo has everything you need, including how to install it and how to use the 256 colorspace provided by base16-shell. https://github.com/chriskempson/base16-vim

**Comment by jswny** [comment]
I'm also a bit confused about Base 16 after reading through some of the template repositories. I posted an issue about it specific to [Base 16 Vim](https://github.com/chriskempson/base16-vim/issues/208).

Most of the templates use hard-coded hex values in them. Wouldn't that mean that changing the colors in your terminal as described in the original issue here wouldn't change anything in the child programs like Vim which are using a Base 16 color scheme?

**Comment by a-vrma** [comment]
@jswny If you are using termguicolors, then yes. Otherwise, no.

**Comment by mk12** [comment]
@belak Coming back to this two years later…

As [I said above](#issuecomment-475791174), I've been using plain base16 and living with the fact that a few programs use bright colors that map to hard-to-read greys. But now I realized, this whole time I could have just used base16-256 themes! For some reason I had been thinking base16-256 = base16-shell, i.e. that your step (3) is necessary.

But I think base16-shell is just a crutch for terminals that don't support configuring colors 16-255 directly. I use [kitty](https://sw.kovidgoyal.net/kitty/), which does, so there's no need for base16-shell.

**Comment by belak** [comment]
Thanks for all the discussion here!

We're a bit behind, but we've been picking up development in the [base16-project](https://github.com/base16-project) org. I've taken a shortened, reworded version of what @mk12 said above and added it to the README in [this commit](https://github.com/base16-project/base16/commit/a26af221685db790dfc7a36d1fefe699178453f5).
