### ISSUE TITLE
Base16-Default-Dark - iTerm vs VS Code

### ISSUE THREAD

**Issue by jrock2004** [chriskempson/base16#202]
Not sure who should win here. Is VS code or vim wrong here? Maybe my iterm settings are wrong and making vim look off? 

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/655716/68075308-65f77900-fd7c-11e9-9fdd-817013ab5aba.png">

**Comment by belak** [comment]
This is mostly a limitation in differences between what these editors support VS Code is more flexible, so it can more easily use the purple for "keywords" rather than the blue for "functions & methods". Lots of themes in editors like vim have strange limitations and can't always be adapted properly. So, in short VSCode looks more correct, but there probably isn't a ton that can be done to make vim match exactly.

See here for more details about styling guidelines: http://chriskempson.com/projects/base16/#styling-guidelines

**Comment by belak** [comment]
Thanks for bringing this up though, it's a good question.
