### ISSUE TITLE
Bright Colours

### ISSUE THREAD

**Issue by FredHappyface** [chriskempson/base16#210]
Hello, great project it's been great fun creating the templates for KDE Plasma and Windows terminal.

In the case of the latter though, there are no bright variants for many of the colours. Is this something that could be added?

Thanks

**Comment by belak** [comment]
What do you mean by bright variants? Do you mean adding more colors to the spec?

There is a weird disconnect between terminals and base16 because base16 only provides 8 actual colors and 8 shades of grey. This doesn't map cleanly on to a terminal which is why base16-shell and the 256-color variants exist.

**Comment by FredHappyface** [comment]
There's two options that I can think of. One would be extending the spec whilst providing backwards compatibility. And another would involve programmatically generating these colours. Though this would have the drawback of reducing the amount of control that a scheme author has over the end theme

Not sure how useful/ easy to implement that would be

**Comment by jonhoo** [comment]
There are also "dim" variants of colors, which poses a similar problem (see for example https://github.com/aaron-williamson/base16-alacritty/issues/1).

**Comment by FredHappyface** [comment]
That is very true. Pretty much as soon as I created the Base24 Organisation which was to try the former solution I realized this was the case. Again the solutions that I can think of are extend again (though this would get silly) or get the builder to generate dim and bright variants (Eg Base08_Bright)

**Comment by belak** [comment]
I think it *might* be possible to do something if the spec was extended to include optional bright and dim colors, though I don't know how it would be handled if those were not provided by the scheme. Making it so each scheme only needs to provide 8 colors (and 8 shades of gray) has made it super easy for people to make new schemes.

If there was a proposal with an alternative way of handling missing colors, I would be happy to push that forward.

**Comment by FredHappyface** [comment]
Might it be possible to do something like described here?
https://github.com/Base24/base24/blob/master/styling.md

Here is the implementation in python 
https://github.com/Base24/base24-builder-python

The main changes are outlined here
https://github.com/Base24/base24/blob/master/builder.md

I do admit that this solution only solves the issues with bright colours (though I would say that these are significantly more common than dim colours)

What are your thoughts?

**Comment by belak** [comment]
The main issues I've run into are mostly around diffs - providing two green colors and two red colors so they can look decent (I played around with dynamic darken/lighten functions in the emacs themes - https://github.com/belak/base16-emacs/pull/101 - but it's not my favorite solution)

All the work you've done in base24 is pretty impressive - there's a lot of stuff in there I think we could learn from and use here. Is there a reason you went for 2 more shades of black rather than 1 plus a lighter brown? Also, I notice that under styling, you have NA for all the newer colors - it would be nice to have a recommendation around how to use them as well.

There are a few issues I don't know how to solve - base16 works well partially because it's only 16 colors and you can fit it into a terminal color space. Being able to set up base16 in your terminal and have vim just work (tm) is super valuable - once more colors are added, the vim themes (and many other terminal applications) would lag behind, potentially even not working well at all unless you have a 256 color terminal and even there it would just be an approximation.

This would also require changes to lots of schemes and templates - once a template starts using the ligher variants, they would start to look really bad on schemes that don't have them. Maybe this is alright?

I'm hoping to start pushing on #74, but I'm not sure if that will go anywhere. Something like that would make it easier for us to move forward faster on the builder/styling changes because we could officially support them in a smaller subset of "officially maintained" themes while still providing tools to build other themes.

**Comment by FredHappyface** [comment]
Yeah, I find that the diffs do tend to look a little bit rubbish. This is an issue that I have had with the base24 vscode stuff I have been working on recently. 

Thanks very much! The reasons I went for a 'darker' and 'darkest' were largely driven when I was writing base16 kde plasma. I found that many of the dark schemes looked for too bright. In other templates I have found that I have used 'darker' far more than the darkest (base10 and base11 respectively)

The reason I never went with a brown was mainly because it was deprecated in base16 and I am not aware of a terminal making use of that colour. Though part of it was also an oversight.

Recommendations are broken into two main categories as it stands: language syntax - which was mostly addressed by base16, and terminal ansi colours - which hasn't really been defined in the base16 spec. 

The likes of what ansi colour red is is pretty obvious, but then there is the whole thing with using base09 v base0a for ansi yellow. I've found this to be one of the key differences when comparing different templates such as the various windows terminal templates.

One of the key goals of base24 was to provide a high degree of compatibility so that base16 schemes should not look out of place when used with a base24 template (or certainly no worse than if that scheme had been combined with a base16 template)

As a developer, I do make the assumption that everyone is able to access a terminal that supports a minimum of the 16 ansi colours. Many popular terminals do support those 256 colours and an increasing number still supports truecolour

Hopefully the measures that I have put in place have enabled my implementation to be backwards and forwards compatible (this would require the use of a base24 builder in many cases)

The points made in #74 look fantastic. I do hope that it is a success as I think that an organisation would provide a huge benefit to everyone involved with base16

I really like what the dracula theme do with their 'templates' - one can often assume that anything in that organisation is of a reasonable to high quality

**Comment by belak** [comment]
I think the documentation isn't very clear - as far as I know brown isn't deprecated, it's meant for deprecated functions.

It would be a pretty big change, but I think providing bright colors for all the ansi colors would be a big improvement.

```
# These 8 are currently well-defined
base00 | Black
base08 | Red
base0B | Green
base0A | Yellow
base0D | Blue
base0E | Magenta
base0C | Cyan
base05 | White

base03 | Bright Black

# These 6 aren't as well defined - there have been definitions added for them in base24 though
Bright Red
Bright Green
Bright Yellow
Bright Blue
Bright Magenta
Bright Cyan

base07 | Bright White
```

The hard part for me is how to handle a base16 scheme in a base24 template - I don't think that's possible unless you make the restriction that all the bright variants shouldn't be used on top of the normal colors and should only be used as accents. However, this means they can't be used for diffs so that's not still a great improvement.

**Comment by FredHappyface** [comment]
Ah, my misunderstanding there. That would benefit from being clarified in the docs 

Currently what happens is that the standard colour variations are used in place of the bright variations. A large number of base16 templates already do this (I've seen several use base09 for yellow and base0a for bright yellow)

**Comment by belak** [comment]
Right, that makes sense, but my point is that if a template was designed to use bright red for a diff foreground and normal red for the background, but a scheme doesn't define that, when that template displays a diff, it won't actually be visible because the foreground and background would be the same.

**Comment by FredHappyface** [comment]
Yeah it would be up to the scheme designer to deal with that in that case. 

Not sure how one could design the spec/ builder to work around that. Perhaps the builder could calculate the bright variant in that case but then that adds complexity

**Comment by belak** [comment]
I think the only way to really work around it is to specify that the bright variants should only be used as accents and to be very careful if you're placing the accent color on the main color because they may actually be the same thing.

**Comment by FredHappyface** [comment]
Yeah, I would entirely agree with that. In which case it would be beneficial to update the documentation to reflect that

**Comment by FredHappyface** [comment]
I had a bunch of time today so I decided to propose a few changes to the base24 spec. This would cause issues with all base16 builders and schemes. But it does add a few colours that could prove useful in gui environments 

https://github.com/Base24/base24/blob/master/future.md

Do you think this sort of thing might be workable?
