### ISSUE TITLE
Question about overwriting

### ISSUE THREAD

**Issue by joshgoebel** [chriskempson/base16#256]
> In the case where schemes share the same name, a builder will overwrite a perviously generated template file. Should this happen, a builder should show warning messages listing the overwritten template files.

I'm not sure I follow.  What is a "generated template file"... are we talking bout the FINAL built raw output - ie the files generated FROM the template?  Ie, typically in a `themes`, etc folder?

**Comment by belak** [comment]
Yes, that's a good clarification.  I don't remember what the wording is in #250, but I'll leave this open to make sure a clarification gets in.

So, it would be something like this:

> In the case where schemes share the same name, a builder will overwrite files previously generated from the template. Should this happen, a builder should show warning messages listing the overwritten files.

**Comment by joshgoebel** [comment]
And when we say "name" are we talking about slug?  Should it perhaps just say slug and be ever more explicit?

**Comment by belak** [comment]
Yes, it should say slug - "name" is left over from the 0.8.0 definition of slug, where I don't think it was as clear, so some used the template name and some used the filename. Now that it's better defined, we can use that term.

**Comment by joshgoebel** [comment]
I reached out to Chris to offer helping out on base16 to catch up on some of the dormant PRs (since 2019), should I instead of been talking to you? :-)

**Comment by belak** [comment]
Chris hasn't been active since 2019. I have commit access, but that's unfortunately it, so I can't add new collaborators. There's a bit of a discussion in #74, but I haven't acted on it yet because I'd like to avoid making a large decision like that with only a few people giving input (and only one person who's been consistently available, even if not always active, me).

In any sense, most of the PRs which have been left open I either forgot about or there's an open question. I'd love some extra help triaging and getting them ready though!

**Comment by belak** [comment]
Just realized that in 0.10.0 this won't be an issue at all because there will be one list of slugs and they can't overlap because they're from a single folder.

**Comment by belak** [comment]
This was resolved when we merged in [spec 0.10.0](https://github.com/base16-project/base16#0100-mar-20-2021) as a part of the migration to the [base16-project](https://github.com/base16-project) org.

If you still see this as an problem, please open a new issue in the [new repo](https://github.com/base16-project/base16).
