### ISSUE TITLE
What to do with complex templates?

### ISSUE THREAD

**Issue by vbwx** [chriskempson/base16#52]
I'm opening this issue for "brainstorming" purposes.
There are apps (e.g., the Terminal of macOS) and IDEs (e.g., Visual Studio) whose profiles/themes have complex formats (binary data, Base64-encoded data, and the like) that can't be covered with simple templating. However, I think these apps should not be deprived of base16; are separate builder programs necessary to handle these formats?

**Comment by chriskempson** [comment]
Ideally the base16-builder spec should be kept simple. I've decided that base16-builders will by default only deal with simple text-replacement when creating templates. Without this limitation a builder could grow wildly in terms of complexity and features and I'm keen to avoid that.

However, I see no harm in creating forks of existing builders (or creating your own) to deal with a specific editor/application. Such a builder could still implement and adhere to the official spec (with exceptions) and make use of the schemes repo but any template that requires such a builder would have to be excluded from the templates repo.

**Comment by iamthad** [comment]
I was wondering the same thing about multiple-file themes, for example those used by [textual](https://github.com/FroZnShiva/base16-textual). It seems to me this might be simpler to implement than binary theme files.

**Comment by Gwyki** [comment]
I ran into this issue a few days ago when I attempted to port a set of scripts that I built to generate templates for Tilda. The problem here is that there isn't really a theme definition for Tilda - so I had to resort to each template being a script that I can then run to directly modify the relevant .config entries. Obviously not ideal.

So I guess I have an application specific "builder". Where does such hacky methods fit into this new framework?

**Comment by belak** [comment]
I think the base16-gnome templates do the same thing - a script which runs and sets the proper values... for stuff like tilda, that's probably the best option.

**Comment by chriskempson** [comment]
@Gwyki If I understand you correctly, the scripts generated from your template can be built by any builder. If so this doesn't sound like an application specific Builder. If Tilda doesn't have its own theme files than modifying .config entries with a script sounds like the only way of doing this?

**Comment by belak** [comment]
I think it may be time to revisit this and/or come up with a policy on this. There's a template sitting in the templates source which doesn't actually work with any builders (it uses a custom build.sh script and requires the python builder) which is what was recommended.

Maybe we should specify the difference between base16 templates and "built with base16" since there are repos popping up as templates which only use the base16 infrastructure to build things, but don't work as a valid template.

**Comment by lgranie** [comment]
I wrote https://github.com/lgranie/base16-builder-bash
I add a output entry by file in template

**Comment by belak** [comment]
This would be partially solved by the 0.10.0 spec proposal in #250, as it clarifies that builders should be focused on building one theme at a time and does away with the base16-templates-source repo, so a broken template won't break builds for everyone. It means that complex templates could still be in the README, but may require a specific builder.

**Comment by belak** [comment]
This was (somewhat) resolved when we merged in [spec 0.10.0](https://github.com/base16-project/base16#0100-mar-20-2021) as a part of the migration to the [base16-project](https://github.com/base16-project) org.

If you still see this as an problem, please open a new issue in the [new repo](https://github.com/base16-project/base16).
