### ISSUE TITLE
Advice wanted: Web interface built on top of base16

### ISSUE THREAD

**Issue by graysonwright** [chriskempson/base16#63]
Hello, @chriskempson!

I'm a huge fan of the work you've done with base16, and think it's a great standard for defining and sharing colorschemes. Thanks for all your work.
## I built a thing

[I created a tool](http://colors.graysonwright.com) based on base16 that allows users to preview themes on a web page, before using a base16 builder to generate config files for that theme. The base16 theme is stored entirely in the URL, which makes it easy to share with others. For an example of how this works, check out:
- Default Dark: http://colors.graysonwright.com/#181818,282828,383838,585858,b8b8b8,d8d8d8,e8e8e8,f8f8f8,ab4642,dc9656,f7ca88,a1b56c,86c1b9,7cafc2,ba8baf,a16946
- Tomorrow: http://colors.graysonwright.com/#ffffff,e0e0e0,d6d6d6,8e908c,969896,4d4d4c,282a2e,1d1f21,c82829,f5871f,eab700,718c00,3e999f,4271ae,8959a8,a3685a
- Mexico Light: http://colors.graysonwright.com/#f8f8f8,e8e8e8,d8d8d8,b8b8b8,585858,383838,282828,181818,ab4642,dc9656,f79a0e,538947,4b8093,7cafc2,96609e,a16946
- Materia: http://colors.graysonwright.com/#263238,2C393F,37474F,707880,C9CCD3,CDD3DE,D5DBE5,FFFFFF,EC5F67,EA9560,FFCC00,8BD649,80CBC4,89DDFF,82AAFF,EC5F67

For each of these themes, you can click the "Download" link on the bottom of the page to get a ZIP file with all of the base16 config files for that theme.
## Advice wanted

I built most of this project in January, and it fell by the wayside for a few months. Back when I built it, I used the [base16-builder](https://github.com/chriskempson/base16-builder/blob/master/base16) Ruby implementation that you wrote ([see the commit](https://github.com/graysonwright/colors/commit/69dde4658e5981c4aafc51d74c88e9b0e9cdd55b)), which has since been deprecated. That repository gave me a base16-builder implementation and many templates to work off of.

As you know, the repository that I used has since been deprecated. I'd like to update my project to follow the new base16 project guidelines, but I'm not sure what the best approach would be to update my project.

If you have a moment, could you take a look at how I'm using base16, and suggest some pointers for updating my project to conform to the new base16 spec & guidelines? A few specific questions that I have are:
- Does [the `base16-builder` implementation](https://github.com/chriskempson/base16-builder/blob/master/base16) that I borrowed from you still conform to the base16 spec?
- It seems like the base16 template files are now distributed among many different repositories. Is there a recommended way to keep those templates up to date in my project?

Thanks for your help, and for your great work in creating this standard!

Cheers,
Grayson

**Comment by chriskempson** [comment]
Hi @graysonwright,

Just got around to taking a look at this and I really like what you've built. I've been wanting to build something like that for a while now as it is a great tool for designing colour schemes and an interesting way of sharing them too.

As for updating your project, if you wish to continue using Ruby then you might want to modify the old script a little so that it conforms to the new spec (https://github.com/chriskempson/base16/blob/master/builder.md) and create a base16-builder-ruby repository as we don't yet have a Ruby implementation that follows the new spec (see: https://github.com/chriskempson/base16#builder-repositories for a current list).

As you've already noticed the new template files are kept within their creators repositories. Git is used to keep these templates up to date (I've just updated to builder spec to make this clearer). An example of this can be seen in the PHP implementation (https://github.com/chriskempson/base16-builder-php/blob/master/src/Builder.php) particularly the fetchSources and updateSources methods.

Hope this helps and be sure to add your project to https://github.com/chriskempson/base16#projects-using-base16 😄
