### ISSUE TITLE
Use GitHub organizations feature to lower fragmentation

### ISSUE THREAD

**Issue by dumblob** [chriskempson/base16#74]
As per https://github.com/mawww/kakoune/issues/65#issuecomment-252862524 from @delapouite, it would make sense to not leave one person (@chriskempson) to be the bottle neck (mainly due to time constraints) of this great project. But transfer the responsibility to an organization. GitHub offers a very easy to setup and easy to use solution.

Could you take a look at it @chriskempson ?

**Comment by chriskempson** [comment]
Base16 is just an idea described by the guidelines in this repository. If described well enough, I don't see how I'd be a bottleneck. For example, someone who can accept PRs faster than I, could fork base16-vim then this new repo can be listed in base16-templates-source and I'll drop my repo. Only issue is, this someone would have to know the ideas in my head for how things should look exactly because they aren't described well enough yet.

I'm currently using the vim/textmate templates as a way of describing the syntax highlighting. In other words, I've made the classic developer mistake of development before design. Though I guess a design document wouldn't have got very far on its own.

What I really want to be working on now (and would love some help with) is creating an HTML doc that looks something like http://chriskempson.github.io/base16/ but for many languages instead of many themes. This could be used as a reference with the styling guidelines. When I've completed this task I'll likely end up maintaining just this repo and the source repos.

If someone wants to go ahead and create an organisation and gets everyone to agree to putting their builders, schemes and templates in there then that's fine. Personally, I'm not so keen on the idea of having a base16 organisation as I don't see the need but as I'm only interested in sharing my idea and helping others take that further, whatever the community sees as the best way to do this is fine by me.

**Comment by dumblob** [comment]
>What I really want to be working on now (and would love some help with) is creating an HTML doc that looks something like http://chriskempson.github.io/base16/ but for many languages instead of many themes. This could be used as a reference with the styling guidelines.

Oh, I completely missed this underlying idea. Then you're totally right - a [HIG](https://en.wikipedia.org/wiki/Human_interface_guidelines )-like wiki-structured document would be the best solution.

So, the current TODO might look like this:

1. Communicate this main/only goal very clearly to the community. E.g. through one sentence (motto?) in bold right at the top of all places regarding base16 (including GitHub repositories) with a pointer to the central HIG-like HTML document.

1. Opening appropriate GitHub Issue(s) representing particular tasks for the HIG-like HTML document (a preliminary table of contents or work breakdown structure might be sufficient) to show the community what you're going to do and what you'd like to being helped with.

1. Closing this GitHub Issue as invalid as a GitHub organization seems useless (at least for the time being) for the goal you described.

**Comment by belak** [comment]
Personally, I'd like to see something like this happen as well... currently, if following the "official" repos, it still relies on you to merge things into the lists.

There's already another group which split off a while back and is still maintaining separate templates and a builder purely because there weren't any updates in the main repo for a period of several months. It would be great to avoid this in the future.

**Comment by dumblob** [comment]
@belak could you please point us to the "another group which split" (I'm not orienting myself very well in base16 forks and related repos)? Thanks.

**Comment by chriskempson** [comment]
@dumblob yep that TODO list looks spot on 🙂

@belak this is true, however I think I can cope with merging the two source repos.

**Comment by belak** [comment]
@dumblob https://github.com/base16-builder/base16-builder

I think there's been a bit of discussion with them in the past, but I haven't been following it lately.

**Comment by belak** [comment]
I forgot I reserved `base16-themes` ages ago just in case we want to go through with this... I may also see about contacting the person who goes by `base16` (purposefully not at-mentioning them because we haven't really made a decision) because that would be best (if we decide to go through with changing the name)

**Comment by dumblob** [comment]
@belak thanks for the update. I'm curious how this'll evolve.

**Comment by actionless** [comment]
i see in this repo there is already quite a number of pull requests, oldest of them are submitted more than half a year ago

would you mind moving base16, scheme and template source indexes repositories to a github organization? so things could still keep going when you're not around

**Comment by belak** [comment]
@chriskempson Would you be willing to consider this? There's an issue that was opened in January (#181) asking if this is alive still because it doesn't look like you've been available for updates to base16 since November. I would be happy to help with this as these are themes I use every day.

**Comment by niklaas** [comment]
It would be great to give the community more control over the codebase of the individual projects. For example, chriskempson/base16-vim#197 not being solved, although the fix would be simple, hinders others to use the most recent version of vim.

**Comment by belak** [comment]
I've temporarily created the @base16-project org and forked the main 3 repos (this one, templates source, and schemes source) to start including changes. All the relevant sources from these 3 repos have been included as changes and a PR back to these repos has been made to make it easier if we move back to these in the future. My go builder now points to these repos by default.

If Chris ever determines officially moving repos to an org would be useful, I'd be happy to remove them so they can be transferred. My goal is to avoid making backwards incompatible changes (at least for now) while still retaining the spirit of the project. I'd be happy to add anyone as a contributor who's been consistently active here and/or maintains a base16 related project.

Unfortunately the name @base16 isn't available, as it's an actual github user and they seem to use that name everywhere, so I doubt they'd be willing to give it up.

**Comment by niklaas** [comment]
@belak, I just read https://github.com/chriskempson/base16/issues/181#issuecomment-497228340. Seems you could officially become contributor and @chriskempson temporarily stepped back from the project.

I've no experiences working with GitHub organizations yet but would be happy to include https://github.com/niklaas/base16-blink to either @base16-project or any other organization that will emerge. Please ping me if you need any help.

**Comment by chriskempson** [comment]
@niklaas Does that mean you'd have to transfer ownership of base16-blink to said organisation or is there another way of including your project? Forgive my asking but I've not used the organisations feature before.

**Comment by niklaas** [comment]
@chriskempson Yes, I think so. I just took a quick look at https://help.github.com/en/articles/transferring-a-repository. I would transfer the repository to said organiation.

**Comment by belak** [comment]
Using an org would be nice because then you can create groups of people (rather than adding a bunch of people to separate repos). I think it would only make sense to transfer blink to an org if the plan was to move all the repos there for people who wanted to.

I definitely would for base16-emacs and base16-builder-go if that was an option - it would be a way of adding more visibility and making it easier to manage long term.

I renamed and archived the forks for now so if you wanted to transfer any repos to @base16-project, they shouldn't conflict. Also when you transfer a repo, as long as you don't make a new one in the same place, Github will redirect clones internally.

**Comment by niklaas** [comment]
> I think it would only make sense to transfer blink to an org if the plan was to move all the repos there for people who wanted to.

Yep, just ping me if that's the way you'll go and your ready. :-)

**Comment by chriskempson** [comment]
like the fact that some people have their repos hosted on alternative services 😃

**Comment by belak** [comment]
People wouldn't be required to transfer them, but it would be an option for people who wanted to. It would allow for more of a focus on community-maintained templates rather than a focus on a single person.

**Comment by chriskempson** [comment]
So that means some repos in the org some repos out of the org. Understood.

Are templates/schemes big enough projects to require maintenance by a community? Could it be said that the community already maintains these repos with PR's?

**Comment by belak** [comment]
In some sense, yes, they already are maintained by the community.

I was imagining something like https://github.com/sensu-plugins, where people have the option of putting their repo in a common place, but aren't forced to if they don't want to. This increases the likelihood that if someone steps away it will still be possible to get fixes merged in that template repo. I've had to deal with this in Oh-My-ZSH and Prezto... those projects are still recovering because it took so long to get anything merged.

In general, I think there are more advantages than disadvantages, though it does involve some change.

Advantages:

- An "official" place to put commuinity-maintained repos (as an option - not required) to make them easier to find
- Easier to maintain who has access (and easier for people to see that information)
- Easier to maintain templates when the maintainer disappears (forks are painful and rarely get everyone on board)
- Easier to build common tooling (I've had ideas about building something which could automatically update template repos when color schemes change)
- If repos are transferred rather than copied (and replacements aren't created in the original location), most users will get updates when they simply `git pull`

Disadvantages:

- Not strictly needed
- Repos would be in a new location (but shouldn't be a huge issue with the automatic redirects github puts in place)

**Comment by reyemxela** [comment]
I think it would definitely help with templates, colorschemes probably less so. Schemes don't necessarily need to change much (at all), but templates, depending on the application, might need to change somewhat often.

Just as another example, currently if you open the [vscode](https://github.com/golf1052/base16-vscode) template, vscode throws a lot of warnings about deprecated/unsupported syntax. I made a PR to fix those, plus improve readability on a few things with too-similar grey colors. But the repo hasn't been updated in a while, so I'm not sure the author is still around.

Like I said, just another example I thought of while reading this thread. :)

**Comment by chriskempson** [comment]
@belak Thanks for that detailed response. I am a bit worried that you'll end up with a group of people who have responsibility for others templates, even in cases where they lack the required skills to maintain them. It would be hard for a Vim user to take ownership of Emacs repo for example but perhaps this could work, I just feel it's beyond the scope of the base16 project.

@reyemxela Thanks for vscode example.

For me, base16 is an idea laid out in guidelines combined with a few central repos to help realise this. Template custody is a new project goal that changes the direction of the base16 project (which was never meant to put in place methods for dealing with external issues like the unmaintained repos of others).

Having had some more time to think about this, I've realised I don't want base16 to become an org. However, perhaps a separate entity (such as a "base16-team" org) can have separate goals to the base16 project such as the goal of looking after unmaintained templates or schemes that others wish to transfer (if that's what its members want).

**Comment by actionless** [comment]
i still think having the org would be the best option

also inside org you can have subgroups

so, in example you described above, if some user would volunteer to support only vim template:

you could create new group `vim-support` and give it permission only to vim template repo

**Comment by chriskempson** [comment]
@actionless No need for subgroups, the structure of https://github.com/sensu-plugins org that @belak pointed out looks like it would work 😄 I've created a base16-templates org to transfer one of my unmaintained repos and will experiment with it.

**Comment by belak** [comment]
@chriskempson I've also got base16-project if you want that - I'd be happy to transfer it

**Comment by chriskempson** [comment]
@belak Thanks but I think the name 'base16-project' is a bit too all encompassing, 'base16-templates' states the job of the org better as per 'sensu-plugins' 😄

**Comment by belak** [comment]
You're welcome to use the logo I made for the base16-project org. I can export it as a png of any size (since it's a vector), or any number of other formats if you'd like to use it.

**Comment by chriskempson** [comment]
Thanks! I grabbed a 512px PNG from your org and have applied it to the templates org.

**Comment by belak** [comment]
I've exported it as an SVG. I'll look at removing the logo from base16-project to make it clearer it's not official.
https://gist.github.com/belak/8b7afd3ca3d2618cbcf00c7b53ebde48

**Comment by chriskempson** [comment]
Great, I've grabbed a copy thanks 👍

**Comment by FredHappyface** [comment]
Is this something that you are still considering? As there are quite a few pull requests still in the pipeline. For example, windows terminal which had I known about I probably wouldn't have duplicated efforts.

**Comment by a-vrma** [comment]
I will give my opinion even though no one asked:

I think https://github.com/chriskempson/base16-schemes-source, https://github.com/chriskempson/base16-templates-source, and https://github.com/chriskempson/base16 should definitely be community-owned.
I don't really get having the actual templates and schemes be community-owned though. Generally, they were made by one person who knows them inside and out. If there are problems with the maintainer being absent, then fork, but there is no point doing it before then. If you link to them from a central source -- as you already do -- then the average user can find them easily.

**Comment by actionless** [comment]
agree with a-vrma

also, we again have a situation when there are almost one year old PRs waiting to be merged:
https://github.com/chriskempson/base16/pulls

**Comment by belak** [comment]
I do agree - I think this should be moved to an org and that the officially supported templates should be community maintained as well. However, I don't think @chriskempson has any current plans to do this - I try to go through PRs as often as I can... the one PR that's getting close to a year old has a related question on a linked PR that was never answered - it wasn't merged on purpose.

I'm happy to take a look at any PRs, and I fully admit I've been falling behind lately.

If anyone wants to put a proposal together, I'd be happy to run with it.

**Comment by FredHappyface** [comment]
I think that's the whole idea of creating an org. Just to spread that load so people who are contributing feel like those contributions are useful but also appreciating that for those who merge those contributions, that they have other priorities and a life alongside open source. And hopefully, helping us all find that balance.

Thanks for everything you are contributing to this project and community 😁

**Comment by belak** [comment]
These are the ideas I've been interested in:

- Move to an org of some sort, hopefully with more community involvement to reduce burden on the existing maintainers. I still have @base16-project, though that is inactive at the moment, the result of merging changes from a hard fork back into the official repos.
- Move templates/scheme yaml source files into the main repo - having to clone 3 repos plus all the repos those point to seems a bit complicated. 
- Start looking at having a number of "officially" supported templates with an active maintainer - moving vim into community maintained, emacs, potentially others. This is one of the biggest wins in my book. We could also look into adopting templates which have active maintainers and are kept up to date.
- Update the builder spec to specify that builders should be focused on building a single template at a time - this would allow us to remove the template source yaml file and simply include links in the README and would make it easier to include as a part of CI in those template repos. This is technically possible now without an org, but it would potentially break builders.

Does anyone have other ideas or things they'd like to see out of a change?

Unfortunately, while I am a maintainer, I don't have approval (or permission) to move these repositories, so this would either need to be done as a hard fork (which I'd like to avoid) or @chriskempson would need to agree.

**Comment by FredHappyface** [comment]
They sound great. I think I hacked about the python builder so that it would only grab a local set of templates

(this ultimately became the base24 portable builder) but I'd be very happy to strip out the non base16 elements and contribute that if that is something that falls in line with point 4

**Comment by a-vrma** [comment]
> Move templates/scheme yaml source files into the main repo - having to clone 3 repos plus all the repos those point to seems a bit complicated.

Agreed.

> Update the builder spec to specify that builders should be focused on building a single template at a time

@InspectorMustache's base16-builder-python already does this with its `--scheme` and `--template` options. I think if we want to change the spec we should involve the maintainers of currently compliant builders. @ilpianista maintains the Rust one.

In other news, I'm developing a new version of the base16-vim template without any function logic that's based on the color scheme writing best practices described in [vim-colortemplate](https://github.com/lifepillar/vim-colortemplate). Would love to add that to the organization after it's done.

**Comment by a-vrma** [comment]
The first beta release of the [new template](https://github.com/a-vrma/base16-vim) is out. How can we move it to @base16-project?

**Comment by belak** [comment]
Currently, the @base16-project is archived because I was added as a contributor here, however, it would be nice to get a few more people on these repos and move towards something that's more community owned. Once that's done, we can look at moving base16-vim (and potentially other repos as well)

@chriskempson would you be alright with moving some repos to the @base16-project namespace so we're not limited to contributor changes only when you're available?

**Comment by FredHappyface** [comment]
I'd be very happy to be involved some way with this if needed 🙂

**Comment by actionless** [comment]
if it gonna be decided to proceed with organization, i also wanna be part of it

**Comment by Misterio77** [comment]
I'd love to help as well

**Comment by Z5483** [comment]
Bump

I'm curious as to what is the current state of this discussion.

**Comment by belak** [comment]
As far as I'm aware, there's been no movement, but here's the state as I see it:

* There are very few active maintainers on base16 (the spec/color schemes)
* No (current) plans to move to a Github org (though I have @base16-project and @base16-themes reserved for this purpose because base16 is taken by someone).

There are a few ways forward for this:

1. Fork base16 as-is to allow for more community ownership. This would be an alright temporary fix but would probably not be great long term.
2. Fork base16 and make some tweaks to fix up minor issues (like repo structure). This would maintain backwards compatibility, with schemes and templates, but would require changes to builders and doesn't fix a number of issues I (personally) have with how base16 is designed.
3. Fork base16 and make larger tweaks to fix up minor and major issues (like repo structure, missing "bright" colors, and the base16-shell problem). This is a bigger change and would involve the most work (as it would be backwards incompatible with themes and templates, though they shouldn't all need major tweaks), but it is admittedly the one I'm the most interested in. This is probably large enough that it would involve a name change... and yes, I am aware that this would [create a conflicting standard](https://xkcd.com/927/).

What do other people think would be the best option? If the community wants to directly fork base16, I would be happy to help get that started, but I don't know if I'll stick around long term.

**Comment by Misterio77** [comment]
In my personal opinion, i would prefer 2 (or 1, if it's easier).
The xkcd is relevant as always, and i (personally) think the standard (even if not perfect) works nicely right now and is flexible enough. We have a lot of very nice schemes and templates, and having to reconform them to the standard (even if it's small tweaks) would be too much work, i think. It would also fragment current and future contributions.

Having the spec and listings on the same repo, or, even better, having all templates and schemes themselves together would greatly improve contribution and usage (for builders, third party apps, etc).
One of the problems i ran into when building flavours was that some schemes include completely unnescessary files in the repo (one or two palette images are fine... but [base16-vice](https://github.com/Thomashighbaugh/base16-vice-scheme) has giant random wallpapers, it takes a lot of bandwidth to clone).
Having them together on our repo could help making everyone commit just the scheme files themselves (fixing the additional files issue i mentioned), we could even fix problems with abandoned or broken schemes/templates, add user contributed subtemplates to existing templates (a lot of templates are fully stale and won't accept PRs for more generalized subtemplates).

Importing all existing schemes and templates (without requiring any modifications whatsoever) into the central repo would be really quick and easy.

**Comment by belak** [comment]
So, the tweaks I would make with option 2:

* Move all schemes into the spec repo
* Remove the templates-source and schemes-source repos
* Recommend that builders are focused on building 1 template at a time - in general builders should be used by maintainers and shouldn't be needed by most people.

All these changes would be clarified in the spec.

The issues which wouldn't be resolved:

* base16 does not map to the 16 colors needed for a terminal color scheme (if you include bright colors).
* base16 does not have bright/dark variants of colors (you only really need one of those). This makes things like a git diff hard to display properly (See https://github.com/belak/base16-emacs/pull/93 and https://github.com/belak/base16-emacs/issues/57. I even went as far as adding a "darken" modifier in that repo in order to work around this issue). This is not fixable without changing which colors the color schemes provide.
* base16-shell is a hack which works well-enough but is extremely hard to get working properly for many people and even harder to help debug. This hack is needed because base16 doesn't map well onto terminal schemes.

**Comment by belak** [comment]
> Having the spec and listings on the same repo, or, even better, having all templates and schemes themselves together would greatly improve contribution and usage (for builders, third party apps, etc).

This is how it was originally. It wasn't very maintainable. I do think the builder approach has been good overall, but it needs some tweaks.

> Importing all existing schemes and templates (without requiring any modifications whatsoever) into the centralized repo would be really quick and easy too. So this would preserve all current and future contributions to this repo.

Yes, it's theoretically possible, but templates are probably not likely. base16 moved away from that for many reasons and it would be a shame to repeat the same mistakes. Additionally, it's a licensing nightmare - each of the templates would have to be licensed under their own licenses, separate from the base16 spec and color schemes, which is much easier if they stay in their separate repos.

**Comment by Misterio77** [comment]
While i personally don't miss bright colors too much (making them bold with the normal colors is readable enough for me), i do see why it could be troublesome for some.

We could perhaps release a 0.10 revision including +8 colors (and trying to make them backward compatible, perhaps? builders could default to the current 8 trim colors if the bright ones aren't present in the scheme).
We could either try to get Chris' blessing for that, or releasing under a new name (base24? haha) as you suggested.

**Comment by Misterio77** [comment]
I see the problem with managing them all together... Hmm. We already have a rule that all schemes/templates should be MIT, right? Maybe we could do a contributer agreement about licensing them under the spec?

If that is not feasable, just having the sources together with the spec in a org would be better than what we current have, i think. I think this would at least easen the burden of managing 3 separate repos?

**Comment by belak** [comment]
I believe @FredHappyface attempted a base24 org a while back. I'm not sure how that went. I unfortunately don't know how we could add colors in a backwards compatible way without shoving complexity on the templates and users.

If we moved to 24 colors, it raises questions about how to map those colors to the 16 colors of a terminal... and how that would interact with terminal applications like vim if a terminal only supports 16 colors.

> I see the problem with keeping everything together... Hmm. We already have a rule that all listed schemes/templates should be MIT, right? Maybe we could do a contributer agreement about licensing them under the spec?

This isn't necessarily possible either - often times schemes are ports of other color schemes, "owned" by other people. Requiring a CLA might cause issues there.

> If that is not feasable, just having the sources together with the spec in a org would be better than what we current have, i think. I think this would at least easen the burden of managing 3 separate repos?

Yes, this was the idea behind my proposal to move all scheme files to the repo, drop the base16-*-source repos and recommend that builders focus on building 1 template repo at a time.

**Comment by FredHappyface** [comment]
I mean the Base24 org addresses some of those larger issues for me as far as bright colours go in a backwards compatible way. If you're going to use gh stars to measure success then it's not got a huge following or anything (10 stars I think). Happy to work with a team of maintainers but as has pretty much already been outlined, there are only a few that seem able to put any time towards this and I'm not sinking hours into something to not get noticed/ used (I'd rather put that time into other commitments or software that people will find useful)

I think I've said this before but I'm perfectly happy to work with this project/ the next great idea but there's some key sustainability issues to having a "one man band" project

**Comment by Misterio77** [comment]
It seems that Fred's base24 is actually pretty well thought out and tackles most issue we discussed (backwards compatibility, ansi mapping, etc), but adoption seems to be a problem, sadly :c

Maybe for now just centralizing the spec and listings under an org would be a good enough improvement? We could at least tackle the maintenance issue for now, and once everyone migrates, we can think about building upon the spec with new features (such as adding new colors in the same way base24 did?)?

**Comment by belak** [comment]
I'm on board with that. I've added @chriskempson to both @base16-project and @base16-themes. Previously he said he wasn't interested in base16 becoming a full org - could we make these changes to the spec, move schemes into this repo, and start putting themes in @base16-themes? Or would it be better to try and move everything to @base16-project?

**Comment by Misterio77** [comment]
I personally think trying to get @base16 from the owner (or github support?) could be worthwhile (if at all possible). I think having everything under @base16-team is the next best option. Then would you rather have separate spec and schemes (with the schemes themselves, not just a listing) repos? Or would just a single `base16` one make more sense?

**Comment by belak** [comment]
We would not be able to get `base16` from GitHub support as they actually have repos there. Additionally, they seem to go by base16 everywhere and I doubt they'd be willing to give it up: http://arvind.me/

I've opened a support ticket with GH support to see if we can get @base16-team because I don't have access to it.

A separate schemes repo would probably be a good idea. We can actually transition old builders to the new setup by pointing them at the new schemes repo.

**Comment by belak** [comment]
I've opened https://github.com/chriskempson/base16/pull/250 for the repo simplification. It contains a link to both an [implementation of the proposed spec](https://github.com/belak/base16-builder-go/pull/16) and [a repo with all schemes](https://github.com/belak/base16-schemes).

I'll post an update once I hear back from GitHub support.

**Comment by belak** [comment]
Github responded saying that @base16-team isn't available because someone is actually using it, just as a private org so you can't see activity. If anyone here is holding it, we can still use it, otherwise we'll have to use @base16-project or @base16-themes.

**Comment by joshgoebel** [comment]
@belak I'd like to say that having an organization is working really well for Highlight.js.  I'd highly recommend that the 3 key repos be moved into an organization that's community/team owned.  Best case would be to do this with @chriskempson blessing rather than a hard fork... but if he's really off doing other stuff and almost completely out of things and a hard fork would be super beneficial then...

We also allow 3rd party contributors to host language grammars and plugins at the organization (but don't require it)... and it has exactly the benefit mentioned earlier:

> This would increase the likelihood that if someone steps away it will still be possible to get fixes merged in that template repo. 

It also allows the core team to more easily keep tabs and weigh in on PRs and such things to help out when it makes sense. I don't see any need for *multiple* organizations... it's easy enough to have teams inside organizations with different permissions on different repos... having more than one organization just seems ridiculously complex and I think would make things *harder* to manage?

Also one of these comments mentioned mixing/merging repos... getting away from this current pattern where it takes TWO PRs just to add a new template or theme would be nice... not sure why the `yaml` directories couldn't be moved into the main repo and then a single PR could be easily reviewed and it would be much easier to manage adding new themes and templates.

**Comment by joshgoebel** [comment]
I like @base16-project if we're voting. :-)

**Comment by belak** [comment]
Thanks for weighing in!

> @belak I'd like to say that having an organization is working really well for Highlight.js. I'd highly recommend that the 3 key repos be moved into an organization that's community/team owned. Best case would be to do this with @chriskempson blessing rather than a hard fork... but if he's really off doing other stuff and almost completely out of things and a hard fork would be super beneficial then...

Yeah, the hard fork is looking more likely. Thankfully, as I mentioned before, I still have commit access, so we can add a disclaimer to these repos.

> We also allow 3rd party contributors to host language grammars and plugins at the organization (but don't require it)... and it has exactly the benefit mentioned earlier:
> 
> > This would increase the likelihood that if someone steps away it will still be possible to get fixes merged in that template repo.
> 
> It also allows the core team to more easily keep tabs and weigh in on PRs and such things to help out when it makes sense. I don't see any need for _multiple_ organizations... it's easy enough to have teams inside organizations with different permissions on different repos... having more than one organization just seems ridiculously complex and I think would make things _harder_ to manage?

I agree with all of this.

> Also one of these comments mentioned mixing/merging repos... getting away from this current pattern where it takes TWO PRs just to add a new template or theme would be nice... not sure why the `yaml` directories couldn't be moved into the main repo and then a single PR could be easily reviewed and it would be much easier to manage adding new themes and templates.

There's some historical context here - one of the earlier versions of base16 was everything-in-one repo. It included the builder, the schemes, and the templates all in one place. My personal opinion is that the current version (with the builders being required to include the URL of a repo which when downloaded contains a single yaml file which points to other repos) is a slight over-correction from that.

My proposed solution (in #250) is to move all schemes to one repo, making both the schemes and builders easier to maintain. Additionally re-focusing the builder spec on building a single template repo at a time will remove a number of edge cases (there have been problems in the past where a single push to someone else's template repo actually broke the build process for someone else, because the build process in the spec is very specific about what commands should do).

We can even make the the template change backwards compatible by replacing the base16-schemes-source with a single entry pointing to the combined themes repo and can leave the base16-templates-source repo as-is without breaking any existing builders.

**Comment by joshgoebel** [comment]
> We can even make the the template change backwards compatible by replacing the base16-schemes-source with a single entry pointing to the combined themes repo and can leave the base16-templates-source repo as-is without breaking any existing builders.

Wait, wouldn't that break the paths?

**Comment by belak** [comment]
Essentially, list.yaml would be replaced with this:

```
combined: https://github.com/base16-project/base16-schemes
```

The names of all of the schemes will stay the same. Because builders should be building based off the list.yaml file, they should be able to build using the combined schemes repo with no additional tweaks.

**Comment by joshgoebel** [comment]
AH, because we're talking schemes - not templates. :)  That might have been my confusion... themes already allow multiple themes per repo... so you'd just be putting all the themes into one big directory.  I got it now. :)

**Comment by xicreative** [comment]
I've been lurking on this issue on and off for a while hoping @chriskempson might make an appearance and give his blessing for an org but it seems like he's been MIA for well over a year. Given that his personal website is no longer online, I think he may unfortunately be out of the picture for good.

I'd volunteer for some of the duties getting base16 moved over to an org; it's something I use almost every day in one form or another and believe its certainly worth maintaining.

**Comment by dumblob** [comment]
Is here still someone who has at least commit rights to this repository? If so, could you help @xicreative to transfer as much stuff to an organization?

**Comment by belak** [comment]
> Is here still someone who has at least commit rights to this repository? If so, could you help @xicreative to transfer as much stuff to an organization?

Yep, I'm still here. I'll try to take a look at copying some stuff over later today.

**Comment by joshgoebel** [comment]
I don't have a lot of time, but I'm also happy to be added as a contributor to the organization and help out where I can.  Also don't see any reason the nodejs-builder (which I now maintain) couldn't be moved into the organization as well if that was desirable.

**Comment by JamyGolden** [comment]
I'd also be willing to help contribute to moving things forward and maintaining.

**Comment by belak** [comment]
Alright, there's still more to do, but I've started working on this. Here's where we are so far:

* The base16-project exists (as well as base16-project-contrib) - currently I am the only owner and collaborator, but I expect that to change as more people step up. I'm currently open to adding people who have submitted base16-related projects before. Additionally, if you show a number of high-quality contributions, that's another way to get added as a maintainer.
* Spec v0.10.0 has been merged (along with the Go builder) and as a result the [base16-schemes](https://github.com/base16-project/base16-schemes) repo has been created.
* Documentation has been updated in the [base16 spec repo](https://github.com/base16-project/base16).
  * Templates have been split into "official", "contrib" and "unofficial"/"community" with a short description of each.
  * Schemes have been moved to the schemes repository README
  * Emacs, Vim, and Shell have been adopted as "official" templates.
* The [base16-emacs](https://github.com/base16-project/base16-emacs) repo has been moved to base16-project and a [PR has been submitted](https://github.com/melpa/melpa/pull/8044) updating the location the package is cloned from when building.
  * This also included updates to comply with the Melpa

That's what I can remember doing, though I might have forgotten something.

I could use some help making sure the READMEs are up to date and have clearer documentation. The changes I made were sort of thrown together. Additionally, something to replace the original website would be really nice (even if it's just getting the website up on github pages somewhere initially). I could also use some help getting any schemes that haven't been merged yet into the schemes repo (as well as any templates being submitted here).

My TODO list:

* Contact Github support to make the base16-project/* repos are the "primary" repos and the chriskempson ones show up as forks.
* Add more new collaborators
* Improve the base16-builder-go to make the build process easier
* Look at adding CI for updating the schemes repo and maybe auto-updating template repos
* Clear a bit of the PR backlog
* Look at migrating existing issues and PRs (either automatically or by hand)
* Update the README of this repo to point to the new location and mention the "archived"-ish status.

@joshgoebel I'd definitely be open to moving the nodejs-builder to base16-project. At least for now, I've introduced a fairly strict requirement on "official" builders to be up to date with the latest spec. Unfortunately because I merged spec 0.10.0, I think the nodejs-builder might need an update. I realize that's a bit unfair - I did it this time to move fairly quickly.

@JamyGolden It looks like you forked the base16-textmate/sublime templates. Is that something you'd be interested in maintaining?

**Comment by JamyGolden** [comment]
I don't use Sublime or Textmate anymore, but I'd be happy to maintain the project. I'm interested in maintaining/co-maintaining the shell and vim repos too.

**Comment by joshgoebel** [comment]
> I realize that's a bit unfair 

Yes, it seems unfair, and also a bit impractical I think for where we are right now (as a budding organization).  New specs will come and go, the various maintainers may update the "official" builders as they have the time.  I'm not sure placing such an onerous requirement on anyone right out of the gate paints this great new step forward in the best light.

What if we first get all the repos we wish centralized and then work on making sure that they all conform to the v0.10 spec?  I think a clear disclaimer that a certain client doesn't yet meet the v0.10 spec should be more than sufficient in the meanwhile.

Thoughts?

**Comment by belak** [comment]
@joshgoebel Sure, I'm open to that... Most of my changes were thrown together pretty quickly but should be fairly uncontroversial. The v0.10.0 spec was merged because it's been sitting there for a year and hasn't had any major unaddressed comments.

Just as a note the v0.10.0 spec was sitting in PR form for over a year and I had a base16-builder-go update ready to go with the release - I just know that the specs have a tendency to sit for months and don't often change much, so I was hoping it wouldn't be too crazy to require builders to be updated. Maybe specifying that at least one official builder must have a PR ready before a spec change can be merged would be enough.

I do want to provide binary releases of the go builder as well, but that's a side note.

If you have a suggestion for updating the README, please submit a PR for now and I'll aim to get you added to the org later today.

**Comment by joshgoebel** [comment]
Should i go ahead and figure out how to submit a transfer for the repo to the organization then?

**Comment by belak** [comment]
> Should i go ahead and figure out how to submit a transfer for the repo to the organization then?

Yeah, I'll make sure to update the readme with our decision.

**Comment by dumblob** [comment]
@belak just a friendly note any organization shall have at least 2 **owners** (not just maintainers) to shield against one owner disappearing.

I for myself have already moved several public projects under an organization in an event of person disappearance and all of them have the policy of giving every member **owner** rights and so far I did not experience any vandalism and it actually proved very helpful as everybody could do technically speaking everything and everybody seemed to feel "important" by getting this level of trust.

But of course for projects with hundreds of contributors this doesn't work. Though it is one of the best starting points I am familiar with.

Btw. it's enormously important to define and publish **acceptance criteria** for PRs. That sets everybody's expectations to the same level, enables distributed independent reviews, and does not have the bottle neck of waiting for certain people to submit "the right PR".

**Comment by belak** [comment]
@dumblob That's a fair point. I'm not sure I'm ready to give owner permissions to everyone though, especially when I barely know anyone. So far everyone I've added has write permissions to all base16 repos, and I expect to keep doing that. I'll look into adding people as admins of specific repos though as a stopgap, especially if they're transferred in.

If anyone steps up to help with day-to-day operations (merging PRs, fixing issues, etc) adding more people as owners will be an easy task. Throughout the life of base16, very few people have shown interest in doing that.

I will wait to contact Github support to change the "primary" repos until after there are multiple owners to make it easier for someone to start something else up if I disappear before that point.

I agree that having clear expectations around what's expected to get a PR merged would be helpful - if nobody else ends up doing that, I'll try to put something together in the next week or so. I already tried to clarify expectations around getting repos added to the org.

**Comment by JamyGolden** [comment]
Is there somewhere we can talk about the project that's not on this issue? A discord/slack/irc?

**Comment by joshgoebel** [comment]
> If anyone steps up to help with day-to-day operations 

If I have time.  I wouldn't mind being an admin of base16-node-builder again though in the meantime...

I think clear communication is most important thing for any project/organization... projects start dying when issues/PRs/whatever just sit with no one responding... even a confusing policy can be dealt with if someone is at least talking to you - though I do agree that clear expectations never hurt. :-)

**Comment by dumblob** [comment]
@JamyGolden I would say starting low is the way to go - namely to make a new issue for such "transfer discussions" in the new repository under the new GitHub organization.

This is to prevent to further scattering of the community - simply because the community here is **guaranteed** to already have a GitHub account and not many would want to create account on discord/slack/irc/... just for base16. Of course, for chat and advice discord/slack/irc is fine, but for resolving the important organizational stuff now so much needed, I think GitHub issue is the best thing to choose.

**Comment by belak** [comment]
I've added teams to @base16-project for each project, added people who have mentioned interest in maintaining those to those teams, and given teams the "Manage" permission in the relevant repos.

@joshgoebel Sorry, that was an oversight - I've added you back as an admin to the base16-project/base16-builder-node repo.

@JamyGolden I do agree that this issue is probably not the best place for a long term discussion. I've opened https://github.com/base16-project/base16/issues/1 for some of the project convention/migration discussion. Github issues should be the place for anything that needs input from other people. I've also created #base16 on Libera Chat (IRC) for anyone who wants more real time communication because my bouncer is idling on Libera all the time anyway.

@dumblob That's a good idea on transfer discussions - I've added it to the backlog in the linked issue.

**Comment by belak** [comment]
@Misterio77 I just sent you an invite. :) Let me know if there are any specific templates/builders you want to work on and I'll add you to the respective teams.

**Comment by belak** [comment]
I've posted a large deprecation notice in this repo - https://github.com/chriskempson/base16/#deprecated

In the new repo, we have https://github.com/base16-project/base16/issues/1 and https://github.com/base16-project/base16/issues/2 which we'll use for collaboration moving forward.

Thanks to everyone for joining in and helping out!
