### ISSUE TITLE
Underscored Slugs and Slugs without Special Characters

### ISSUE THREAD

**Issue by jfelchner** [chriskempson/base16#89]
This was also a problem in the original builder (as a bug) and continues to be a problem (because mustache is logicless).

In order to create a template for something like `vim-airline` I need access to a slug that either has dashes converted to underscores or removed entirely.  Currently if a scheme doesn't provide a slug and has multiple words, dashes are used between the words.

**Comment by belak** [comment]
Maybe introducing an additional variable to the builder would help? What would it be called?

**Comment by jfelchner** [comment]
I think there needs to be an underscored version and a completely sanitized version with any special characters removed.

**Comment by chriskempson** [comment]
The way I'd do this is fork a builder of your choice, make the necessary changes to the code and release the output. Base16 is never going to be able to support everything and nor is it intended too hence the reason why it has been kept so simple. The idea is that people can take really simple builder and customise them for their own purposes if needs be.

There should probably be an area added to the readme for template specific builder repos as I know a few of these already exist.

**Comment by belak** [comment]
@jfelchner Most special characters should be removed, as the slug should be based on the filename. However, that means dashes may be used rather than underscores... I would be willing to add a variable to [my base16 builder](https://github.com/belak/base16-builder-go) for it, but I'm not sure what it should be called or what exactly should be sanitized.

For now, I've added `scheme-slug-sanitized` which replaces `-` with `_` but I'm not a huge fan of that name if it just replaces dashes.
